services:
  # Backend API Service
  - type: web
    name: byte-club-backend
    env: node
    plan: free
    buildCommand: cd backend && npm install && npm run build
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: JWT_EXPIRES_IN
        value: 7d
      - key: REFRESH_TOKEN_EXPIRES_IN
        value: 30d
      - key: LOG_LEVEL
        value: info
      - key: RAPIDAPI_JUDGE0_KEY
        sync: false
      - key: RAPIDAPI_JUDGE0_HOST
        value: judge0-ce.p.rapidapi.com
